using System;
using Microsoft.CodeAnalysis;

namespace Example.SourceGen
{
    [Generator]
    public class Generator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            context.AddSource("StringFactory", @"// This file was autogenerated
namespace Example.Generated
{
    public static class StringFactory
    {
        public static string GetString() => ""Generated"";
    }
}");
        }

        public void Initialize(GeneratorInitializationContext context) { }
    }
}
